### PR TITLE
grunt watch will jshint and test

### PR DESCRIPTION
**Pull request by jakech**
@louisbuchbinder

### CODE REVIEW

**Comment by jakech** [comment]
Sorry, its a big one.

**Comment by jakech** [comment]
I have moved `/algorithm` inside `/scripts`.
Also put all tests files in `/spec`.

**Comment by louisbuchbinder** [comment]
Okay. Everything seems to be working for me! Everything you're doing in grunt looks good. I like the .jshintrc and how you modularize.

**Comment by louisbuchbinder** [comment]
I will merge with you so pull yours first

**Pull request merged**
